action: train
mode: ann
l: 4
t: 4
extra_t: 0
bs: 64
lr: 0.01
epochs: 30
id: mymodel1
seed: 42
data: cifar10
dim: 384
num_heads: 12
patch_size: 4
mlp_ratio: 4
save: True
save_acc: True
model_path: ./mymodel1/model0.pt
inherit: True
use_maxpool: True
use_amp: True